server:
  port: 81
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gil-log/spring-cloud-config-practice
          search-paths: cloud-config-file/**
          default-label: master
